### ISSUE TITLE
 response status code 429 Too Many Requests

### ISSUE THREAD

**Issue by Makaaveli** [projectdiscovery/notify#81] opened 2021-09-09 09:44 UTC
![Screenshot (91)](https://user-images.githubusercontent.com/65100125/132663299-85a16437-1f3b-44f8-8527-fb03ecbca35c.png)

Discord issue

**Comment by Makaaveli** [comment] 2021-09-09 09:45
discord issue..

**Comment by ehsandeep** [comment] 2021-09-14 09:18
Hi @Makaaveli, thanks for reporting this, the root cause of this is same as https://github.com/projectdiscovery/notify/issues/79, as such closing this issue, will be resolved as soon as we add rate-limit support.

**Closed by ehsandeep** 2021-09-14 09:18 UTC
